# Generated by Django 3.2.4 on 2023-11-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('About', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni')], max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('yearOfPassing', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('yearsOfExperience', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('currentScore', models.IntegerField()),
                ('techStack', models.TextField()),
                ('courses', models.TextField()),
                ('plan', models.IntegerField()),
                ('endorsements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postedTime', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('metaData', models.CharField(max_length=100)),
                ('likes', models.TextField()),
                ('comments', models.TextField()),
                ('likesCount', models.IntegerField()),
                ('commentsCount', models.IntegerField()),
                ('forumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forum')),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userdetails')),
                ('tags', models.ManyToManyField(to='main.Tag')),
            ],
        ),
    ]
