# Generated by Django 3.2.4 on 2023-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_conversation_hackathon_hackathonregistration_seminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='metaData',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='endorsements',
            field=models.TextField(default='[]'),
        ),
    ]
