# Generated by Django 3.2.4 on 2023-12-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231128_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='techStack',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='techStack',
            field=models.ManyToManyField(to='main.TechStacks'),
        ),
    ]
