# Generated by Django 3.2.4 on 2023-12-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231202_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techstacks',
            name='user',
        ),
    ]
