# Generated by Django 3.2.9 on 2023-12-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userdetails_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('organization', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('participants', models.TextField(default='')),
                ('status', models.BooleanField()),
                ('mentoredBy', models.CharField(max_length=100)),
                ('interestedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='registeredCount',
            field=models.IntegerField(default=0),
        ),
    ]
