# Generated by Django 5.0 on 2023-12-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20231210_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='techStack',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
